// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_hero: dynamic(() => import("./AboutHero")),
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  geo_hero: dynamic(() => import("./GeoHero")),
  marquee_tile: dynamic(() => import("./MarqueeTile")),
};
